# Jekyll configuration for SirsiNexus GitHub Pages
title: "SirsiNexus"
description: "Agent-embedded Infrastructure Platform"
baseurl: "/SirsiNexus"
url: "https://sirsinexusdev.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: null

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
  - README.md
  - target/
  - Cargo.toml
  - Cargo.lock
  - src/
  - analytics-platform/
  - core-engine/
  - ml-platform/
  - ui/
  - docs-backup/
  - .git/
  - .gitignore

# Include static files
include:
  - _redirects

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Committee Collection
collections:
  committee:
    output: true
    permalink: /committee/:name/
