apiVersion: v1
kind: ConfigMap
metadata:
  name: sirsi-config
  namespace: sirsi-nexus
  labels:
    app: sirsi-nexus
data:
  # Core Engine Configuration
  core-config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      grpc_port: 9090
      metrics_port: 9091
    
    database:
      url: "postgresql://root@cockroachdb-service:26257/sirsi_nexus?sslmode=disable"
      max_connections: 20
      min_connections: 5
      connection_timeout: 30
    
    redis:
      url: "redis://redis-service:6379"
      max_connections: 10
    
    telemetry:
      metrics_enabled: true
      logging_level: "info"
    
    hypervisor:
      max_agents: 1000
      scheduler_interval: 5
      resource_monitoring: true
      auto_scaling: true
  
  # Nginx Configuration
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream frontend {
            server frontend-service:3000;
        }
        
        upstream core-engine {
            server core-engine-service:8080;
        }
        
        upstream analytics {
            server analytics-service:8000;
        }
        
        server {
            listen 80;
            server_name _;
            
            location / {
                proxy_pass http://frontend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/ {
                proxy_pass http://core-engine/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /analytics/ {
                proxy_pass http://analytics/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
  
  # Prometheus Configuration
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'core-engine'
        static_configs:
          - targets: ['core-engine-service:9091']
        metrics_path: /metrics
        scrape_interval: 5s
      
      - job_name: 'analytics'
        static_configs:
          - targets: ['analytics-service:8000']
        metrics_path: /metrics
        scrape_interval: 10s
      
      - job_name: 'cockroachdb'
        static_configs:
          - targets: ['cockroachdb-service:8081']
        metrics_path: /_status/vars
        scrape_interval: 10s
      
      - job_name: 'redis'
        static_configs:
          - targets: ['redis-service:6379']
        scrape_interval: 10s
