apiVersion: v1
kind: Secret
metadata:
  name: sirsi-secrets
  namespace: sirsi-nexus
  labels:
    app: sirsi-nexus
type: Opaque
data:
  # Base64 encoded values - CHANGE IN PRODUCTION
  jwt-secret: c2lyc2luZXh1cy1qd3Qtc2VjcmV0LWNoYW5nZS1tZQ==
  db-password: cGFzc3dvcmQ=
  redis-password: cmVkaXNwYXNzd29yZA==
  grafana-admin-password: YWRtaW4xMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: sirsi-nexus
  labels:
    app: sirsi-nexus
type: kubernetes.io/dockerconfigjson
data:
  # Docker registry credentials - configure with your registry
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwicGFzc3dvcmQiOiJwYXNzd29yZCIsImF1dGgiOiJkWE5sY201aGJXVTZjR0Z6YzNkdmNtUT0ifX19
