---
name: Security Vulnerability Report
about: Report a vulnerability in the project
title: '[Security Issue] '
labels: 'security'
---

## Description
A clear and concise description of what the vulnerability is.

## Impact
Explain what kind of impact this vulnerability might have.

## Steps to Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior
A clear and concise description of what you expected to happen.

## Proof of Concept
(optional) Add any relevant code snippet or additional details that help to demonstrate the vulnerability.

## Environment
- Platform/OS: [e.g., Windows, MacOS, Linux]
- Browser: [e.g., Chrome, Safari]
- Version: [e.g., v0.6.0-alpha]

## Additional context
Add any other context about the problem here.
