#!/bin/bash

echo "==========================================="
echo "Firebase Hosting Custom Domain Setup"
echo "==========================================="
echo ""
echo "Your site is deployed at: https://sirsi-nexus-live.web.app"
echo ""
echo "Since Firebase CLI doesn't support adding custom domains directly,"
echo "you need to:"
echo ""
echo "1. Open Firebase Console (opening now...)"
firebase open hosting:site

echo ""
echo "2. Click 'Add custom domain' and enter: sirsi.ai"
echo ""
echo "3. Firebase will show a TXT record for verification"
echo ""
echo "==========================================="
echo "EXACT DNS RECORDS FOR GODADDY:"
echo "==========================================="
echo ""
echo "Step 1 - Add Verification TXT (from Firebase):"
echo "  Type: TXT"
echo "  Name: @"
echo "  Value: [Firebase will show this - starts with google-site-verification=]"
echo "  TTL: 1 hour"
echo ""
echo "Step 2 - After verification, add these A records:"
echo "  Record 1:"
echo "    Type: A"
echo "    Name: @"
echo "    Value: 151.101.1.195"
echo "    TTL: 1 hour"
echo ""
echo "  Record 2:"
echo "    Type: A"
echo "    Name: @"
echo "    Value: 151.101.65.195"
echo "    TTL: 1 hour"
echo ""
echo "Step 3 - Add WWW redirect:"
echo "  Type: CNAME"
echo "  Name: www"
echo "  Value: sirsi-ai.web.app"
echo "  TTL: 1 hour"
echo ""
echo "Step 4 - Restore email autodiscover:"
echo "  Type: CNAME"
echo "  Name: autodiscover"
echo "  Value: autodiscover.outlook.com"
echo "  TTL: 1 hour"
echo ""
echo "==========================================="
echo "RECORDS TO DELETE IN GODADDY:"
echo "==========================================="
echo ""
echo "Delete any A records with these GitHub Pages IPs:"
echo "  - 185.199.108.153"
echo "  - 185.199.109.153"
echo "  - 185.199.110.153"
echo "  - 185.199.111.153"
echo ""
echo "==========================================="
echo "VERIFICATION COMMANDS:"
echo "==========================================="
echo ""
echo "After DNS propagation (15-30 mins), run:"
echo ""
echo "  dig sirsi.ai"
echo "  curl -I https://sirsi.ai"
echo ""
echo "==========================================="
echo ""
echo "Press Enter to open GoDaddy DNS management..."
read
open "https://dcc.godaddy.com/control/sirsi.ai/dns"
